site_name: Gitxray
site_url: https://www.gitxray.com/
repo_url: https://github.com/kulkansecurity/gitxray
theme:
  name: readthedocs
  language: en
  features:
    - navigation.expand
    - content.code.copy

nav:
  - 'installing.md'
  - 'awesome_features.md'
  - 'more_features.md'

markdown_extensions:
  - toc:
      permalink: ïƒ
  - attr_list
  - md_in_html

copyright: |
  Made with &hearts; by <a href="https://www.kulkan.com" target="_blank">Kulkan Security</a> - your favorite <a href="https://www.kulkan.com" target="_blank">Penetration Testing Partner</a>.
